# Generated by Django 4.2.30 on 2026-05-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockreceipt_total_amount_due_stockreceipt_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceipt',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
